all:
	#gene compression
	gcc -o in_filter in_filter.c
	gcc -o out_filter out_filter.c
	#name compression
	gcc -o namecomp namecomp.c

gene:
	gcc -o in_filter in_filter.c
	gcc -o out_filter out_filter.c

name:
	gcc -o namecomp namecomp.c

qual:
	
clean: 
	rm -f in_filter out_filter namecomp		
